// <auto-generated />
#pragma warning disable
﻿using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Content.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class ContentLifecycleAndS3Multipart : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "ContentTypeMime",
                schema: "content",
                table: "Contents",
                type: "character varying(127)",
                maxLength: 127,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "FailureReason",
                schema: "content",
                table: "Contents",
                type: "character varying(500)",
                maxLength: 500,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "OwnerUserId",
                schema: "content",
                table: "Contents",
                type: "character varying(128)",
                maxLength: 128,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "QuarantineReason",
                schema: "content",
                table: "Contents",
                type: "character varying(500)",
                maxLength: 500,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "S3UploadId",
                schema: "content",
                table: "Contents",
                type: "character varying(256)",
                maxLength: 256,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Sha256Checksum",
                schema: "content",
                table: "Contents",
                type: "character varying(64)",
                maxLength: 64,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "Status",
                schema: "content",
                table: "Contents",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "UploadKind",
                schema: "content",
                table: "Contents",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<DateTime>(
                name: "ValidatedAt",
                schema: "content",
                table: "Contents",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Contents_OwnerUserId",
                schema: "content",
                table: "Contents",
                column: "OwnerUserId");

            migrationBuilder.CreateIndex(
                name: "IX_Contents_Status_CreatedAt",
                schema: "content",
                table: "Contents",
                columns: new[] { "Status", "CreatedAt" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Contents_OwnerUserId",
                schema: "content",
                table: "Contents");

            migrationBuilder.DropIndex(
                name: "IX_Contents_Status_CreatedAt",
                schema: "content",
                table: "Contents");

            migrationBuilder.DropColumn(
                name: "ContentTypeMime",
                schema: "content",
                table: "Contents");

            migrationBuilder.DropColumn(
                name: "FailureReason",
                schema: "content",
                table: "Contents");

            migrationBuilder.DropColumn(
                name: "OwnerUserId",
                schema: "content",
                table: "Contents");

            migrationBuilder.DropColumn(
                name: "QuarantineReason",
                schema: "content",
                table: "Contents");

            migrationBuilder.DropColumn(
                name: "S3UploadId",
                schema: "content",
                table: "Contents");

            migrationBuilder.DropColumn(
                name: "Sha256Checksum",
                schema: "content",
                table: "Contents");

            migrationBuilder.DropColumn(
                name: "Status",
                schema: "content",
                table: "Contents");

            migrationBuilder.DropColumn(
                name: "UploadKind",
                schema: "content",
                table: "Contents");

            migrationBuilder.DropColumn(
                name: "ValidatedAt",
                schema: "content",
                table: "Contents");
        }
    }
}
