apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: content-svc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chidionyema/haworks-platform.git
    targetRevision: HEAD
    path: deploy/helm/content-svc
    helm:
      releaseName: content-svc
  destination:
    server: https://kubernetes.default.svc
    namespace: haworks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
