// <auto-generated />
#pragma warning disable
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Haworks.Privacy.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddErasureTimeoutTokenId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "ErasureTimeoutTokenId",
                schema: "privacy",
                table: "PrivacyRequestState",
                type: "uuid",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ErasureTimeoutTokenId",
                schema: "privacy",
                table: "PrivacyRequestState");
        }
    }
}
