// <auto-generated />
#pragma warning disable
// <auto-generated />
using System;
using System.Collections.Generic;
using Haworks.Localization.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Haworks.Localization.Api.Migrations
{
    [DbContext(typeof(LocalizationDbContext))]
    [Migration("20260516000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("localization")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Haworks.Localization.Api.Domain.Translation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Key")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Dictionary<string, string>>("Values")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.HasKey("Id");

                b.HasIndex("Key")
                    .IsUnique();

                b.ToTable("Translations", "localization");
            });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<Guid>("ConsumerId")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("Consumed")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("Delivered")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("ExpirationTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<long?>("LastSequenceNumber")
                    .HasColumnType("bigint");

                b.Property<Guid>("LockId")
                    .HasColumnType("uuid");

                b.Property<Guid>("MessageId")
                    .HasColumnType("uuid");

                b.Property<int>("ReceiveCount")
                    .HasColumnType("integer");

                b.Property<DateTime>("Received")
                    .HasColumnType("timestamp with time zone");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("bytea");

                b.HasKey("Id");

                b.HasAlternateKey("MessageId", "ConsumerId");

                b.ToTable("InboxState", "localization");
            });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
            {
                b.Property<long>("SequenceNumber")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                b.Property<string>("Body")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("ContentType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<Guid?>("ConversationId")
                    .HasColumnType("uuid");

                b.Property<Guid?>("CorrelationId")
                    .HasColumnType("uuid");

                b.Property<string>("DestinationAddress")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<DateTime?>("EnqueueTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("ExpirationTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("FaultAddress")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("Headers")
                    .HasColumnType("text");

                b.Property<Guid?>("InboxConsumerId")
                    .HasColumnType("uuid");

                b.Property<Guid?>("InboxMessageId")
                    .HasColumnType("uuid");

                b.Property<Guid?>("InitiatorId")
                    .HasColumnType("uuid");

                b.Property<Guid>("MessageId")
                    .HasColumnType("uuid");

                b.Property<string>("MessageType")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid?>("OutboxId")
                    .HasColumnType("uuid");

                b.Property<string>("Properties")
                    .HasColumnType("text");

                b.Property<Guid?>("RequestId")
                    .HasColumnType("uuid");

                b.Property<string>("ResponseAddress")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<DateTime>("SentTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("SourceAddress")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.HasKey("SequenceNumber");

                b.HasIndex("EnqueueTime");

                b.HasIndex("ExpirationTime");

                b.HasIndex("InboxMessageId", "InboxConsumerId");

                b.HasIndex("OutboxId", "SequenceNumber");

                b.ToTable("OutboxMessage", "localization");
            });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
            {
                b.Property<Guid>("OutboxId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("Created")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("Delivered")
                    .HasColumnType("timestamp with time zone");

                b.Property<long?>("LastSequenceNumber")
                    .HasColumnType("bigint");

                b.Property<Guid>("LockId")
                    .HasColumnType("uuid");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("bytea");

                b.HasKey("OutboxId");

                b.ToTable("OutboxState", "localization");
            });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
            {
                b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                    .WithMany()
                    .HasForeignKey("InboxMessageId", "InboxConsumerId");

                b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                    .WithMany()
                    .HasForeignKey("OutboxId");
            });
#pragma warning restore 612, 618
        }
    }
}
